### PR TITLE
Add BigInt support and Unicode handling

### LINKED ISSUE #2: About Unicode
The '🦄🌈'.charCodeAt(0) is 55358. It out of the byte range.

https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function#FNV-1a_hash
```
   hash = FNV_offset_basis
   for each byte_of_data to be hashed
   	hash = hash XOR byte_of_data
   	hash = hash × FNV_prime
   return hash
```

### LINKED ISSUE #3: Support higher bit variants
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/fnv1a/issues/3)

FNV1a can be done in 32-, 64-, 128-, 256-, 512-, and 1024-bit flavors. Currently only 32-bit is implemented, because of JS integer limitations. Now that we have `BigInt` in JS, we can implement the other flavors.

More info: http://www.isthe.com/chongo/tech/comp/fnv/index.html#FNV-source

PR welcome :)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Submitted pull Requests
- [#7 Add BigInt support](https://issuehunt.io/r/sindresorhus/fnv1a/pull/7)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/fnv1a/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by broofa**
* Adds support for the fnv1a.bigInt() api suggested in #3.
* Also deals with unicode strings in a way that's consistent with other fnv1a hash implementations. [Edit: This changes the hash for any string that has unicode in it, hence the BREAKING CHANGE action.]

`mocha` and `ava` both puke if you try to do BigInts in them, so I've had to resort to testing with the native `assert` module.  That may or may not be adequate for you.  And `xo` doesn't recognize bigint literals, [nor does ESLint](https://github.com/eslint/eslint/issues/11524), so I've had to remove the linting step from `npm test`.

Note:  I ended up incorporating some of @ShynRou's work for BigInt support.  He should get the IssueHunt bounty for this.

P.S.  FWIW, the legacy implementation (32 bit Numbers) is ~9X faster than the BigInt counterpart.  https://jsperf.com/fnv1a-number-vs-bigint-perf

Fixes #2
Fixes #3
Closes #7
Closes #4

### CODE REVIEW

**Comment by broofa** [comment]
Oh, and if this qualifies for the on BigInt bounty I guess let me know what to do claim that?  Don't particularly need it, but it's an interesting concept and I'm curious what the experience/flow for that is.

**Comment by broofa** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fi.imgflip.com%2Fwgkf1.jpg&token=ping" data-gitmeme-token="ping"></a>

**Comment by sindresorhus** [comment]
@broofa Really sorry for leaving this for so long. Real-life and a way too long PR queue came in the way...

**Comment by sindresorhus** [comment]
> ava both puke if you try to do BigInts in them,

I just tested with latest version of AVA and `BigInt` and `1n` works fine now. Can you bring back AVA as testing?

> And xo doesn't recognize bigint literals, nor does ESLint, so I've had to remove the linting step from npm test.

XO and ESLint support it now. Can you bring back XO?

**Comment by sindresorhus** [comment]
You need to update index.d.ts too.

**Comment by broofa** [comment]
@sindresorhus Updated to use `xo` and `ava`.  I need some guidance on the following, however:
1. I'm not a TypeScript person, so have no idea what I'm doing in `index.d.ts`
2. I updated to `xo@latest`, but it's still failing due to "BigInt is not defined.  no-undef".   (See failing Travis tests)

**Comment by sindresorhus** [comment]
Thank you for your work on this, @broofa 👍

**Comment by broofa** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2Fpa37AAGzKXoek%2Fgiphy.gif&token=carlton" data-gitmeme-token="carlton"></a>

**Pull request merged**
